apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dionysus-planner.fullname" . }}-data
  labels:
    {{- include "dionysus-planner.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
