/**
 * openspec: backup-export — PURE renderer from the backup bundle to
 * Obsidian-ready markdown files. No I/O, fully unit-testable; the
 * /api/backup/markdown route feeds it the same bundle /api/backup
 * returns.
 */

export interface BackupRecipe {
  id: number;
  name: string;
  servings: number;
  rating: number | null;
  variantOfName: string | null;
  tags: string[];
  derivedTags: string[];
  instructions: string;
  lines: Array<{ displayQuantity: number; displayUnit: string; ingredientName: string }>;
}

export interface BackupProduct {
  id: number;
  name: string;
  category: string;
  unitClass: string;
  brand: string | null;
  barcode: string | null;
  /** openspec: ariadne-product-ref — Ariadne Catalog id, null until linked. */
  productId: string | null;
  readyToEat: boolean;
  categories: string[];
  merchantLinks: string[];
  caloriesPerRef: number;
  proteinPerRef: number;
  carbsPerRef: number;
  fatPerRef: number;
}

export interface BackupPantryRow {
  ingredientName: string;
  displayQuantity: number;
  displayUnit: string;
  stockedAt: string | null;
}

export interface BackupBundle {
  exportedAt: string;
  recipes: BackupRecipe[];
  products: BackupProduct[];
  pantry: BackupPantryRow[];
}

export interface BackupFile {
  path: string;
  content: string;
}

/** Filesystem- and Obsidian-safe note name; collisions get the id. */
export function sanitizeNoteName(name: string, id: number, taken: Set<string>): string {
  const cleaned = name
    .replace(/[\\/:*?"<>|#^[\]]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 80);
  const base = cleaned === "" ? `item-${id}` : cleaned;
  const unique = taken.has(base.toLowerCase()) ? `${base} (${id})` : base;
  taken.add(unique.toLowerCase());
  return unique;
}

function yamlList(values: string[]): string {
  return values.length === 0 ? "[]" : `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;
}

function recipeNote(recipe: BackupRecipe): string {
  const lines = recipe.lines
    .map((line) => `- ${line.displayQuantity} ${line.displayUnit}, ${line.ingredientName}`)
    .join("\n");
  return `---
dionysus: recipe
servings: ${recipe.servings}
rating: ${recipe.rating ?? "null"}
variantOf: ${recipe.variantOfName === null ? "null" : JSON.stringify(recipe.variantOfName)}
tags: ${yamlList([...recipe.tags, ...recipe.derivedTags])}
---

# ${recipe.name}

## Ingredients

${lines === "" ? "_none_" : lines}

## Instructions

${recipe.instructions.trim()}
`;
}

function productNote(product: BackupProduct): string {
  const per = product.unitClass === "COUNT" ? "1 count" : product.unitClass === "VOLUME" ? "100 mL" : "100 g";
  const links = product.merchantLinks.map((url) => `- ${url}`).join("\n");
  return `---
dionysus: product
category: ${product.category}
categories: ${yamlList(product.categories)}
brand: ${product.brand === null ? "null" : JSON.stringify(product.brand)}
barcode: ${product.barcode === null ? "null" : JSON.stringify(product.barcode)}
readyToConsume: ${product.readyToEat}
---

# ${product.name}

| per ${per} | value |
| --- | --- |
| Calories | ${product.caloriesPerRef} kcal |
| Protein | ${product.proteinPerRef} g |
| Carbs | ${product.carbsPerRef} g |
| Fat | ${product.fatPerRef} g |
${links === "" ? "" : `\n## Where to buy\n\n${links}\n`}`;
}

function pantryNote(pantry: BackupPantryRow[], exportedAt: string): string {
  const rows = pantry
    .map((row) => `| ${row.ingredientName} | ${row.displayQuantity} ${row.displayUnit} | ${row.stockedAt ?? ""} |`)
    .join("\n");
  return `---
dionysus: pantry-snapshot
exportedAt: ${exportedAt}
---

# Pantry snapshot

| Item | Quantity | Stocked |
| --- | --- | --- |
${rows}
`;
}

export function renderBackupMarkdown(bundle: BackupBundle): BackupFile[] {
  const files: BackupFile[] = [
    {
      path: "README.md",
      content: `# Dionysus backup

Generated by the Dionysus planner on ${bundle.exportedAt}. The
Recipes/ and Products/ folders are REPLACED on every sync — edit in
Dionysus, not here. Backup.json alongside is the lossless export.
`,
    },
  ];
  const recipeNames = new Set<string>();
  for (const recipe of bundle.recipes) {
    files.push({
      path: `Recipes/${sanitizeNoteName(recipe.name, recipe.id, recipeNames)}.md`,
      content: recipeNote(recipe),
    });
  }
  const productNames = new Set<string>();
  for (const product of bundle.products) {
    files.push({
      path: `Products/${sanitizeNoteName(product.name, product.id, productNames)}.md`,
      content: productNote(product),
    });
  }
  files.push({ path: "Pantry.md", content: pantryNote(bundle.pantry, bundle.exportedAt) });
  return files;
}
